= Db Projekt
:sourcedir: ./
:icons: font
:sectnums:
:sectnumlevels: 5
:toc: left
:toclevels: 3
:experimental: true
:linkattrs:

== Daten:
Synthetische lethalität db:
https://synlethdb.sist.shanghaitech.edu.cn/#/download

Orthologie db:
https://omabrowser.org/oma/genomePW/

Essentielle Gene:
https://v3.ogee.info/#/downloads

== TODO:
ERD und relationale Datenbank
-> mit zumindest 2 Organismen (Mensch und Maus)

====
write a professional documentation about assumptions and decisions you have made and include who was responsible for what in your project work
====

== Fragen:
====
make appointments with Prof. Ivcevic to ask questions
-> write down information and questions
====


== Infos:

=== Infos about the theme
Theme: Krebs (=mutierte Zellen vermehren sich, obwohl sie es nicht sollen)

	DNA überall gleich -> Unterscheidung mit Genen

	Synthetische Lethalität: Ist-Zustand: Gen A, Gen B
				 Wenn beide Gesund sind lebt die Zelle
				 Wenn ein Gen Weg ist kann die Zelle noch leben
				 Wenn beide "deaktiviert" sind stirbt die Zelle
				 Weitere Infos in der Doku

	Essentielle Gene: Gene die Essentiell für die Zelle ist -> wenn sie stirbt, stirbt die Zelle

	Forschung werden an Tieren (Bsp.: Mäusen) durchgeführt.
	Dafür gibt es Forschungen, die vergleichen, welche Gene zwischen den
	Menschen und Tieren gleich sind

=== Answered Questions:

es werden keine speziellen Rechte benötigt

Datenbank ist egal (es geht auch SQLITE)

Wir müssen mit der Datenbank herausfinden, welche Gene synthetisch Lethal sind.

-> Prozentuelle Angaben (80% das die Zelle stirbt, wenn Gen A "ausgeschalten" wird)

Wie sollen die Ergebnisse gespeichert/ausgegeben werden? - log von pl/sql

PL/SQL und trigger? - PL/SQL, in das man ein Gen eingibt und welches dann die Daten dazu in der Console ausgibt

Das ist alles in unseren Daten


== Importieren von Daten im SQL-developer
SQL-developer -> Tabellen (rechtsklick) -> Daten importieren -> Datei auswählen
Daten formatieren und fehlerhafte Daten rauslöschen (durchs interpretieren können fehlerhafte Daten entstehen)


