= Db Projekt
:sourcedir: ./
:icons: font
:sectnums:
:sectnumlevels: 5
:toc: left
:toclevels: 3
:experimental: true
:linkattrs:

== Team

* Balint Balazs
* Arwed Schnalzenberger
* Erik Seifried
* Lukas Sonnleitner

<<<
== Daten:
Synthetische lethalität db:
https://synlethdb.sist.shanghaitech.edu.cn/#/download

Orthologie db:
https://omabrowser.org/oma/genomePW/

Essentielle Gene:
https://v3.ogee.info/#/downloads


[plantuml,ucd,png]
----
include::plantuml/ERD.puml[]
----

In der EssentialGenes Tabelle stehen nur die Gene, welche Essenziell sind.

In der Orthology Tabelle stehen die Gene, die zueinander "passen" (orthology). Also zum Beispiel ein Maus-Gen mit einem Menschen-Gen. Was für ein Typ Gen das ist, können wir dann in der Gene Tabelle herausfinden.

Genetypelookup ist einfach damit wir nicht immer 'Mensch' oder 'Maus' schreiben müssen und damit können wir potenzielle Tipp-Fehler verhindern.

In der SynthethicLethality Tabelle stehen 2 Gene, die Zueinander synthetisch Lethal sind mit dem jeweiligen score.

Orthology: ist nur wichtig, welche gene in der Maus, dem Wurm (Caenorhabditis elegans (CAEEL)) und im Menschen ortholog sind und wie sie es sind(type)

=== Daten Gedankengänge
SynLeth: müssen wir wissen, welches Gen Synthetisch Lethal zu welchem anderen sind (mit dem Score zu wie viel Prozent sie es sind)

Essential Genes: wir wollen nur wissen, welche Gene Essentiell sind, um sie auszusortieren. Alles andere ist unwichtig.

== Infos:

=== Infos about the theme
Theme: Krebs (=mutierte Zellen vermehren sich, obwohl sie es nicht sollen)

	DNA überall gleich -> Unterscheidung mit Genen

	Synthetische Lethalität: Ist-Zustand: Gen A, Gen B
				 Wenn beide Gesund sind lebt die Zelle
				 Wenn ein Gen Weg ist kann die Zelle noch leben
				 Wenn beide "deaktiviert" sind stirbt die Zelle
				 Weitere Infos in der Doku

	Essentielle Gene: Gene die Essentiell für die Zelle ist -> wenn sie stirbt, stirbt die Zelle

	Forschung werden an Tieren (Bsp.: Mäusen) durchgeführt.
	Dafür gibt es Forschungen, die vergleichen, welche Gene zwischen den
	Menschen und Tieren gleich sind

=== Answered Questions:

es werden keine speziellen Rechte benötigt

Datenbank ist egal (es geht auch SQLITE)

Wir müssen mit der Datenbank herausfinden, welche Gene synthetisch Lethal sind.

-> Prozentuelle Angaben (80% das die Zelle stirbt, wenn Gen A "ausgeschalten" wird)

Wie sollen die Ergebnisse gespeichert/ausgegeben werden? - log von pl/sql

PL/SQL und trigger? - PL/SQL, in das man ein Gen eingibt und welches dann die Daten dazu in der Console ausgibt -> weitere infos auf zettel

Das ist alles in unseren Daten

NCBI = entrez
-> entrez wird verwendet

*Gene-Tabelle* mit allen Genen anstatt von einzelnen für alle einzelnen Tiere

Ein weiteres Tier


== Importieren von Daten im SQL-developer
SQL-developer -> Tabellen (rechtsklick) -> Daten importieren -> Datei auswählen
Daten formatieren und fehlerhafte Daten rauslöschen (durchs interpretieren können fehlerhafte Daten entstehen)

== Insert Statements
Folder: /sql

Darin sind alle Insert-Scripts und ein DropTable- und ein CreateTables-Script

Bei den Insert Statements benutzen wir:

----
INSERT ALL
    INTO <table> (<val1>, <val2>) VALUES ('abc', 0)
    INTO <table> (<val1>, <val2>) VALUES ('bcd', 0)
SELECT 1 FROM DUAL;
----

Dies macht die db-inserts schneller, da viele auf einmal auf den Server-hochgeladen werden und dazu noch weniger in die Console ausgegeben wird, anstatt das dies für jedes einzeln passiert.

Jedoch gibt es ein limit dafür, weswegen wir die Scripte auf mehrere "INSERT ALL"-Statements aufteilen mussten.

<<<
== Final Select-Statement

----
include::sql/SQL-Select-Statement.sql[lines = 56..]
----
