@startuml
entity MouseGenes {
    gene_id varchar2
    gene_name varchar2
}

entity Orthology {
    mouse_id varchar2
    human_id varchar2
    orthology_type varchar2
}

entity SyntheticLethality {
    gene1_id varchar2
    gene2_id varchar2
    cell_line varchar2
    statistic_score number
}

entity EssentialGenes {
    gene varchar2
}
Orthology }|--|| MouseGenes
MouseGenes ||-r-o| EssentialGenes
MouseGenes ||--o{ SyntheticLethality : "gen 2"
MouseGenes ||--o{ SyntheticLethality : "gen 1"
@enduml